import { Vehicle } from '@/types/vehicle';

function img(make: string, model: string, year: number): string {
  return `https://cdn.imagin.studio/getimage?customer=img&make=${make.toLowerCase()}&modelFamily=${model.split(' ')[0].toLowerCase()}&modelYear=${year}&zoomType=fullscreen`;
}

export const mockVehicles: Vehicle[] = [
  // Ford
  {
    id: 1,
    make: 'Ford',
    model: 'F-150',
    year: 2023,
    trim: 'Lariat',
    description: 'Full-size Truck with advanced towing capability and off-road package',
    msrp: 52000,
    imageUrl: img('Ford', 'F-150', 2023),
    type: 'Truck',
    specs: { engine: '3.5L EcoBoost V6', horsepower: 400, drivetrain: '4WD', transmission: '10-Speed Automatic', mpgCity: 17, mpgHighway: 23, seating: 6 },
    features: ['Pro Trailer Backup Assist', '360° Camera System', 'Heated & Cooled Front Seats', 'SYNC 4 Infotainment', 'B&O Sound System', 'Adaptive Cruise Control'],
  },
  {
    id: 2,
    make: 'Ford',
    model: 'Explorer',
    year: 2022,
    trim: 'XLT',
    description: 'Three-row SUV with seating for seven and Ford Co-Pilot360',
    msrp: 38500,
    imageUrl: img('Ford', 'Explorer', 2022),
    type: 'SUV',
    specs: { engine: '2.3L EcoBoost I4', horsepower: 300, drivetrain: 'AWD', transmission: '10-Speed Automatic', mpgCity: 20, mpgHighway: 27, seating: 7 },
    features: ['Ford Co-Pilot360', 'Third-Row Seating', 'Hands-Free Liftgate', 'Apple CarPlay / Android Auto', 'Wireless Charging', 'Panoramic Vista Roof'],
  },
  {
    id: 3,
    make: 'Ford',
    model: 'Mustang',
    year: 2024,
    trim: 'GT Premium',
    description: 'Iconic Coupe with 5.0L V8 engine and performance exhaust',
    msrp: 47000,
    imageUrl: img('Ford', 'Mustang', 2024),
    type: 'Coupe',
    specs: { engine: '5.0L Ti-VCT V8', horsepower: 450, drivetrain: 'RWD', transmission: '10-Speed SelectShift Automatic', mpgCity: 15, mpgHighway: 24, seating: 4 },
    features: ['Active Valve Performance Exhaust', 'Brembo Brakes', 'MagneRide Damping System', '12" Digital Cluster', 'B&O 12-Speaker Audio', 'Launch Control'],
  },
  {
    id: 4,
    make: 'Ford',
    model: 'Bronco',
    year: 2023,
    trim: 'Outer Banks',
    description: 'Rugged off-road SUV with removable doors and roof',
    msrp: 43500,
    imageUrl: img('Ford', 'Bronco', 2023),
    type: 'SUV',
    specs: { engine: '2.7L EcoBoost V6', horsepower: 330, drivetrain: '4WD', transmission: '10-Speed Automatic', mpgCity: 18, mpgHighway: 22, seating: 5 },
    features: ['Removable Doors & Roof', 'HOSS 3.0 Off-Road System', 'Trail One-Pedal Drive', '12" Touchscreen', 'Locking Rear Differential', 'Marine-Grade Vinyl Seats'],
  },

  // Toyota
  {
    id: 5,
    make: 'Toyota',
    model: 'Camry',
    year: 2023,
    trim: 'XSE',
    description: 'Mid-size Sedan with sporty styling and dynamic handling',
    msrp: 31500,
    imageUrl: img('Toyota', 'Camry', 2023),
    type: 'Sedan',
    specs: { engine: '2.5L 4-Cylinder', horsepower: 203, drivetrain: 'FWD', transmission: '8-Speed Automatic', mpgCity: 28, mpgHighway: 39, seating: 5 },
    features: ['Toyota Safety Sense 2.5+', 'Sport Suspension', 'Wireless Apple CarPlay', 'JBL Premium Audio', 'Panoramic Moonroof', 'Heated & Ventilated Front Seats'],
  },
  {
    id: 6,
    make: 'Toyota',
    model: 'RAV4',
    year: 2024,
    trim: 'Adventure',
    description: 'Compact SUV with all-wheel drive and outdoor-ready accessories',
    msrp: 35200,
    imageUrl: img('Toyota', 'RAV4', 2024),
    type: 'SUV',
    specs: { engine: '2.5L 4-Cylinder', horsepower: 203, drivetrain: 'AWD', transmission: '8-Speed Automatic', mpgCity: 27, mpgHighway: 33, seating: 5 },
    features: ['Dynamic Torque Control AWD', 'Roof Rails', 'Toyota Safety Sense 2.0', 'Apple CarPlay / Android Auto', 'Wireless Charging', 'Heated Front Seats'],
  },
  {
    id: 7,
    make: 'Toyota',
    model: 'Tacoma',
    year: 2023,
    trim: 'TRD Off-Road',
    description: 'Mid-size Truck built for off-road performance with crawl control',
    msrp: 41000,
    imageUrl: img('Toyota', 'Tacoma', 2023),
    type: 'Truck',
    specs: { engine: '3.5L V6', horsepower: 278, drivetrain: '4WD', transmission: '6-Speed Automatic', mpgCity: 18, mpgHighway: 22, seating: 5 },
    features: ['Crawl Control', 'Multi-Terrain Select', 'Locking Rear Differential', 'Bilstein Shocks', 'LED Headlights', 'TRD-Tuned Suspension'],
  },
  {
    id: 8,
    make: 'Toyota',
    model: 'Corolla',
    year: 2022,
    trim: 'SE',
    description: 'Compact Hatchback with responsive handling and fuel efficiency',
    msrp: 22500,
    imageUrl: img('Toyota', 'Corolla', 2022),
    type: 'Hatchback',
    specs: { engine: '2.0L 4-Cylinder', horsepower: 169, drivetrain: 'FWD', transmission: 'CVT', mpgCity: 31, mpgHighway: 38, seating: 5 },
    features: ['Toyota Safety Sense 2.0', 'Sport Suspension', 'Apple CarPlay', 'LED Headlights', 'Adaptive Cruise Control', '7" Touchscreen'],
  },
  {
    id: 9,
    make: 'Toyota',
    model: 'Supra',
    year: 2024,
    trim: '3.0 Premium',
    description: 'Sport Coupe with turbocharged inline-6 and adaptive suspension',
    msrp: 58000,
    imageUrl: img('Toyota', 'Supra', 2024),
    type: 'Coupe',
    specs: { engine: '3.0L Turbocharged I6', horsepower: 382, drivetrain: 'RWD', transmission: '8-Speed Automatic', mpgCity: 22, mpgHighway: 30, seating: 2 },
    features: ['Adaptive Variable Suspension', 'Launch Control', 'Sport Brakes', 'JBL 12-Speaker Audio', 'Digital Cockpit Display', 'Track Mode'],
  },

  // BMW
  {
    id: 10,
    make: 'BMW',
    model: '3 Series',
    year: 2023,
    trim: '330i xDrive',
    description: 'Luxury Sedan with all-wheel drive and driver-focused cockpit',
    msrp: 55000,
    imageUrl: img('BMW', '3 Series', 2023),
    type: 'Sedan',
    specs: { engine: '2.0L TwinPower Turbo I4', horsepower: 255, drivetrain: 'AWD', transmission: '8-Speed Sport Automatic', mpgCity: 24, mpgHighway: 34, seating: 5 },
    features: ['BMW Live Cockpit Professional', 'Driving Assistance Package', 'Harman Kardon Audio', 'M Sport Package', 'Wireless Apple CarPlay', 'Adaptive LED Headlights'],
  },
  {
    id: 11,
    make: 'BMW',
    model: 'X5',
    year: 2024,
    trim: 'xDrive40i',
    description: 'Luxury midsize SUV with panoramic roof and harman/kardon audio',
    msrp: 72000,
    imageUrl: img('BMW', 'X5', 2024),
    type: 'SUV',
    specs: { engine: '3.0L TwinPower Turbo I6', horsepower: 335, drivetrain: 'AWD', transmission: '8-Speed Sport Automatic', mpgCity: 21, mpgHighway: 26, seating: 5 },
    features: ['Panoramic Sky Lounge LED Roof', 'Harman Kardon Surround Audio', 'Executive Package', 'BMW Digital Key', 'Adaptive M Suspension', 'Driving Assistant Professional'],
  },
  {
    id: 12,
    make: 'BMW',
    model: '4 Series',
    year: 2022,
    trim: 'M440i',
    description: 'Sport Coupe with twin-scroll turbocharged engine and M Sport suspension',
    msrp: 66000,
    imageUrl: img('BMW', '4 Series', 2022),
    type: 'Coupe',
    specs: { engine: '3.0L TwinPower Turbo I6', horsepower: 382, drivetrain: 'AWD', transmission: '8-Speed Sport Automatic', mpgCity: 22, mpgHighway: 29, seating: 4 },
    features: ['M Sport Brakes', 'Adaptive M Suspension', 'Harman Kardon Audio', 'Laserlight Headlights', 'M Aerodynamics Package', 'Head-Up Display'],
  },
  {
    id: 13,
    make: 'BMW',
    model: '2 Series',
    year: 2023,
    trim: '230i Convertible',
    description: 'Luxury Convertible with retractable soft top and premium interior',
    msrp: 51000,
    imageUrl: img('BMW', '2 Series', 2023),
    type: 'Convertible',
    specs: { engine: '2.0L TwinPower Turbo I4', horsepower: 255, drivetrain: 'RWD', transmission: '8-Speed Sport Automatic', mpgCity: 24, mpgHighway: 34, seating: 4 },
    features: ['Retractable Soft Top', 'Heated Front Seats', 'Park Distance Control', 'Apple CarPlay', 'M Sport Package', '64-Color Ambient Lighting'],
  },

  // Tesla
  {
    id: 14,
    make: 'Tesla',
    model: 'Model 3',
    year: 2024,
    trim: 'Long Range',
    description: 'All-electric Sedan with 358-mile range and Autopilot included',
    msrp: 48000,
    imageUrl: img('Tesla', 'Model 3', 2024),
    type: 'Sedan',
    specs: { engine: 'Dual Motor Electric', horsepower: 358, drivetrain: 'AWD', transmission: 'Single-Speed Fixed Gear', mpgCity: 134, mpgHighway: 126, seating: 5 },
    features: ['358-Mile Range', 'Autopilot Included', '15.4" Touchscreen', 'Over-the-Air Updates', 'Supercharger Network Access', 'Panoramic Glass Roof'],
  },
  {
    id: 15,
    make: 'Tesla',
    model: 'Model Y',
    year: 2024,
    trim: 'Performance',
    description: 'All-electric SUV with dual motor AWD and 0-60 in 3.5 seconds',
    msrp: 55000,
    imageUrl: img('Tesla', 'Model Y', 2024),
    type: 'SUV',
    specs: { engine: 'Dual Motor Electric', horsepower: 456, drivetrain: 'AWD', transmission: 'Single-Speed Fixed Gear', mpgCity: 117, mpgHighway: 107, seating: 5 },
    features: ['303-Mile Range', '0-60 mph in 3.5s', 'Autopilot', 'Panoramic Glass Roof', '15.4" Touchscreen', 'Full Self-Driving Capability'],
  },
  {
    id: 16,
    make: 'Tesla',
    model: 'Model S',
    year: 2023,
    trim: 'Plaid',
    description: 'Flagship electric Sedan with tri-motor AWD and 1,020 horsepower',
    msrp: 109000,
    imageUrl: img('Tesla', 'Model S', 2023),
    type: 'Sedan',
    specs: { engine: 'Tri Motor Electric', horsepower: 1020, drivetrain: 'AWD', transmission: 'Single-Speed Fixed Gear', mpgCity: 102, mpgHighway: 102, seating: 5 },
    features: ['396-Mile Range', '0-60 mph in 1.99s', 'Tri-Motor AWD', '17" Touchscreen', 'Yoke Steering Wheel', 'Full Self-Driving Capability'],
  },

  // Honda
  {
    id: 17,
    make: 'Honda',
    model: 'Civic',
    year: 2023,
    trim: 'Sport',
    description: 'Compact Sedan with turbocharged engine and Honda Sensing suite',
    msrp: 26500,
    imageUrl: img('Honda', 'Civic', 2023),
    type: 'Sedan',
    specs: { engine: '1.5L Turbocharged I4', horsepower: 192, drivetrain: 'FWD', transmission: 'CVT', mpgCity: 31, mpgHighway: 40, seating: 5 },
    features: ['Honda Sensing Suite', '9" Touchscreen', 'Wireless Apple CarPlay', 'Heated Front Seats', 'Adaptive Cruise Control', 'Lane Keeping Assist'],
  },
  {
    id: 18,
    make: 'Honda',
    model: 'CR-V',
    year: 2024,
    trim: 'EX-L',
    description: 'Compact SUV with leather interior, heated seats, and Apple CarPlay',
    msrp: 34500,
    imageUrl: img('Honda', 'CR-V', 2024),
    type: 'SUV',
    specs: { engine: '1.5L Turbocharged I4', horsepower: 190, drivetrain: 'AWD', transmission: 'CVT', mpgCity: 28, mpgHighway: 34, seating: 5 },
    features: ['Leather Interior', 'Heated Front Seats', 'Wireless Apple CarPlay', 'Power Moonroof', 'Honda Sensing', 'Hands-Free Power Tailgate'],
  },
  {
    id: 19,
    make: 'Honda',
    model: 'Accord',
    year: 2023,
    trim: 'Touring',
    description: 'Mid-size Sedan with hands-free access power trunk and wireless charging',
    msrp: 36000,
    imageUrl: img('Honda', 'Accord', 2023),
    type: 'Sedan',
    specs: { engine: '2.0L Turbocharged I4', horsepower: 192, drivetrain: 'FWD', transmission: '10-Speed Automatic', mpgCity: 29, mpgHighway: 37, seating: 5 },
    features: ['Hands-Free Access Power Trunk', 'Wireless Charging', 'Bose 12-Speaker Audio', 'Heated & Ventilated Seats', 'Head-Up Display', 'Honda Sensing 360'],
  },
  {
    id: 20,
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    trim: 'Hatchback Sport',
    description: 'Compact Hatchback with sporty rear spoiler and 6-speed manual option',
    msrp: 28000,
    imageUrl: img('Honda', 'Civic', 2022),
    type: 'Hatchback',
    specs: { engine: '1.5L Turbocharged I4', horsepower: 180, drivetrain: 'FWD', transmission: '6-Speed Manual', mpgCity: 29, mpgHighway: 37, seating: 5 },
    features: ['Sport Rear Spoiler', '6-Speed Manual Option', 'Adaptive Damper System', '9" Touchscreen', 'Apple CarPlay', 'Honda Sensing'],
  },

  // Chevrolet
  {
    id: 21,
    make: 'Chevrolet',
    model: 'Silverado 1500',
    year: 2023,
    trim: 'LTZ',
    description: 'Full-size Truck with MultiPro tailgate and available diesel engine',
    msrp: 53000,
    imageUrl: img('Chevrolet', 'Silverado 1500', 2023),
    type: 'Truck',
    specs: { engine: '5.3L EcoTec3 V8', horsepower: 355, drivetrain: '4WD', transmission: '10-Speed Automatic', mpgCity: 16, mpgHighway: 20, seating: 6 },
    features: ['MultiPro Tailgate', '360° Camera', 'Bose 7-Speaker Audio', 'Heated Front Seats', 'Power Running Boards', 'Z71 Off-Road Package'],
  },
  {
    id: 22,
    make: 'Chevrolet',
    model: 'Equinox',
    year: 2024,
    trim: 'RS',
    description: 'Compact SUV with sporty RS styling package and wireless Apple CarPlay',
    msrp: 32000,
    imageUrl: img('Chevrolet', 'Equinox', 2024),
    type: 'SUV',
    specs: { engine: '1.5L Turbocharged I4', horsepower: 175, drivetrain: 'FWD', transmission: '6-Speed Automatic', mpgCity: 26, mpgHighway: 31, seating: 5 },
    features: ['RS Sport Styling', 'Wireless Apple CarPlay', '8" Touchscreen', 'Heated Front Seats', 'Rear Park Assist', 'OnStar 4G LTE Wi-Fi'],
  },
  {
    id: 23,
    make: 'Chevrolet',
    model: 'Camaro',
    year: 2023,
    trim: 'SS 1LE',
    description: 'Muscle Coupe with 6.2L V8 and track-focused suspension package',
    msrp: 49000,
    imageUrl: img('Chevrolet', 'Camaro', 2023),
    type: 'Coupe',
    specs: { engine: '6.2L V8', horsepower: 455, drivetrain: 'RWD', transmission: '6-Speed Manual', mpgCity: 14, mpgHighway: 20, seating: 4 },
    features: ['Track-Focused Suspension', 'Brembo Brakes', 'Limited-Slip Differential', 'Recaro Sport Seats', 'Performance Data Recorder', 'Launch Control'],
  },
  {
    id: 24,
    make: 'Chevrolet',
    model: 'Malibu',
    year: 2022,
    trim: 'Premier',
    description: 'Mid-size Sedan with leather interior and Bose premium audio system',
    msrp: 29000,
    imageUrl: img('Chevrolet', 'Malibu', 2022),
    type: 'Sedan',
    specs: { engine: '2.0L Turbocharged I4', horsepower: 250, drivetrain: 'FWD', transmission: '9-Speed Automatic', mpgCity: 22, mpgHighway: 32, seating: 5 },
    features: ['Leather Interior', 'Bose Premium Audio', 'Heated & Cooled Front Seats', '8" Touchscreen', 'Head-Up Display', 'Wireless Charging'],
  },

  // Audi
  {
    id: 25,
    make: 'Audi',
    model: 'A4',
    year: 2023,
    trim: 'Premium Plus',
    description: 'Luxury compact Sedan with quattro AWD and virtual cockpit display',
    msrp: 49500,
    imageUrl: img('Audi', 'A4', 2023),
    type: 'Sedan',
    specs: { engine: '2.0L TFSI Turbo I4', horsepower: 261, drivetrain: 'AWD', transmission: '7-Speed S tronic', mpgCity: 24, mpgHighway: 34, seating: 5 },
    features: ['Audi Virtual Cockpit', 'quattro AWD', 'MMI Touch Display', 'Bang & Olufsen 3D Audio', '64-Color Ambient Lighting', 'Adaptive Cruise Assist'],
  },
  {
    id: 26,
    make: 'Audi',
    model: 'Q5',
    year: 2024,
    trim: 'Prestige',
    description: 'Luxury compact SUV with panoramic sunroof and Bang & Olufsen audio',
    msrp: 62000,
    imageUrl: img('Audi', 'Q5', 2024),
    type: 'SUV',
    specs: { engine: '2.0L TFSI Turbo I4', horsepower: 261, drivetrain: 'AWD', transmission: '7-Speed S tronic', mpgCity: 23, mpgHighway: 28, seating: 5 },
    features: ['Panoramic Sunroof', 'Bang & Olufsen 3D Audio', 'Audi Virtual Cockpit Plus', 'quattro AWD', 'Matrix LED Headlights', 'Massage Front Seats'],
  },
  {
    id: 27,
    make: 'Audi',
    model: 'TT',
    year: 2022,
    trim: 'RS',
    description: 'Sport Coupe with 2.5L five-cylinder turbo and sport-tuned suspension',
    msrp: 68000,
    imageUrl: img('Audi', 'TT', 2022),
    type: 'Coupe',
    specs: { engine: '2.5L TFSI Turbo I5', horsepower: 394, drivetrain: 'AWD', transmission: '7-Speed S tronic', mpgCity: 22, mpgHighway: 29, seating: 2 },
    features: ['RS Sport Exhaust', 'Magnetic Ride Suspension', 'RS Sport Suspension Plus', 'Audi Virtual Cockpit', 'Bang & Olufsen Audio', 'Launch Control'],
  },
  {
    id: 28,
    make: 'Audi',
    model: 'A5',
    year: 2023,
    trim: 'Cabriolet Premium',
    description: 'Luxury Convertible with soft top and Audi virtual cockpit plus',
    msrp: 61000,
    imageUrl: img('Audi', 'A5', 2023),
    type: 'Convertible',
    specs: { engine: '2.0L TFSI Turbo I4', horsepower: 261, drivetrain: 'FWD', transmission: '7-Speed S tronic', mpgCity: 23, mpgHighway: 34, seating: 4 },
    features: ['Power Soft Top', 'Audi Virtual Cockpit Plus', 'Bang & Olufsen Audio', 'Heated Front Seats', '64-Color Ambient Lighting', 'MMI Navigation Plus'],
  },

  // Mercedes-Benz
  {
    id: 29,
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2024,
    trim: 'C 300',
    description: 'Luxury compact Sedan with MBUX infotainment and Burmester audio',
    msrp: 54000,
    imageUrl: img('Mercedes-Benz', 'C-Class', 2024),
    type: 'Sedan',
    specs: { engine: '2.0L Turbocharged I4', horsepower: 255, drivetrain: 'AWD', transmission: '9-Speed Automatic', mpgCity: 22, mpgHighway: 32, seating: 5 },
    features: ['MBUX Infotainment System', 'Burmester Surround Sound', '64-Color Ambient Lighting', 'Active Brake Assist', 'Panoramic Sunroof', 'Heated Front Seats'],
  },
  {
    id: 30,
    make: 'Mercedes-Benz',
    model: 'GLE',
    year: 2023,
    trim: 'GLE 450',
    description: 'Luxury midsize SUV with E-Active Body Control and third-row seating',
    msrp: 79000,
    imageUrl: img('Mercedes-Benz', 'GLE', 2023),
    type: 'SUV',
    specs: { engine: '3.0L Turbo I6 EQ Boost', horsepower: 362, drivetrain: 'AWD', transmission: '9-Speed Automatic', mpgCity: 20, mpgHighway: 26, seating: 7 },
    features: ['E-Active Body Control', 'Third-Row Seating', 'Burmester 3D Surround Sound', 'MBUX Navigation', 'Panoramic Sunroof', 'Adaptive Damping System'],
  },
  {
    id: 31,
    make: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2022,
    trim: 'E 450 Cabriolet',
    description: 'Luxury Convertible with AIRSCARF neck-level heating and nappa leather',
    msrp: 87000,
    imageUrl: img('Mercedes-Benz', 'E-Class', 2022),
    type: 'Convertible',
    specs: { engine: '3.0L Turbocharged I6', horsepower: 362, drivetrain: 'AWD', transmission: '9-Speed Automatic', mpgCity: 20, mpgHighway: 28, seating: 4 },
    features: ['AIRSCARF Neck Heating', 'Nappa Leather Interior', 'Burmester Premium Audio', 'Active Multi-Contour Seats', 'Panoramic Roof', 'MBUX with Augmented Reality'],
  },
  {
    id: 32,
    make: 'Mercedes-Benz',
    model: 'CLA',
    year: 2023,
    trim: 'CLA 250',
    description: 'Entry luxury Sedan with sporty coupe-like roofline and AMG styling',
    msrp: 44000,
    imageUrl: img('Mercedes-Benz', 'CLA', 2023),
    type: 'Sedan',
    specs: { engine: '2.0L Turbocharged I4', horsepower: 221, drivetrain: 'FWD', transmission: '7-Speed DCT', mpgCity: 24, mpgHighway: 36, seating: 5 },
    features: ['AMG Line Exterior', 'MBUX Infotainment', '64-Color Ambient Lighting', 'Wireless Charging', 'LED High Performance Headlights', 'Panoramic Sunroof'],
  },

  // Hyundai
  {
    id: 33,
    make: 'Hyundai',
    model: 'Tucson',
    year: 2024,
    trim: 'N Line',
    description: 'Compact SUV with N Line sport styling, heated seats, and blind-spot monitor',
    msrp: 33000,
    imageUrl: img('Hyundai', 'Tucson', 2024),
    type: 'SUV',
    specs: { engine: '1.6L Turbocharged I4', horsepower: 180, drivetrain: 'AWD', transmission: '8-Speed DCT', mpgCity: 26, mpgHighway: 33, seating: 5 },
    features: ['N Line Sport Styling', 'Heated Front Seats', 'Blind-Spot Collision Warning', '10.25" Navigation Display', 'Wireless Apple CarPlay', 'Smart Power Liftgate'],
  },
  {
    id: 34,
    make: 'Hyundai',
    model: 'Elantra',
    year: 2023,
    trim: 'N',
    description: 'High-performance Sedan with 276hp turbo and track-tuned suspension',
    msrp: 33000,
    imageUrl: img('Hyundai', 'Elantra', 2023),
    type: 'Sedan',
    specs: { engine: '2.0L Turbocharged I4', horsepower: 276, drivetrain: 'FWD', transmission: '8-Speed N DCT', mpgCity: 22, mpgHighway: 30, seating: 5 },
    features: ['N Corner Carving Differential', 'N Grin Shift Mode', 'Brembo Brakes', 'Launch Control', 'Performance Bucket Seats', 'N Road Sense System'],
  },
  {
    id: 35,
    make: 'Hyundai',
    model: 'Ioniq 5',
    year: 2024,
    trim: 'Limited AWD',
    description: 'All-electric SUV with ultra-fast 800V charging and vehicle-to-load capability',
    msrp: 54000,
    imageUrl: img('Hyundai', 'Ioniq 5', 2024),
    type: 'SUV',
    specs: { engine: 'Dual Motor Electric', horsepower: 320, drivetrain: 'AWD', transmission: 'Single-Speed Fixed Gear', mpgCity: 98, mpgHighway: 89, seating: 5 },
    features: ['800V Ultra-Fast Charging', 'Vehicle-to-Load (V2L)', '266-Mile Range', 'Augmented Reality HUD', 'Relaxation Seats', 'Solar Panel Roof'],
  },
  {
    id: 36,
    make: 'Hyundai',
    model: 'Veloster',
    year: 2021,
    trim: 'N',
    description: 'Sport Hatchback with three-door design and performance N DCT transmission',
    msrp: 32500,
    imageUrl: img('Hyundai', 'Veloster', 2021),
    type: 'Hatchback',
    specs: { engine: '2.0L Turbocharged I4', horsepower: 275, drivetrain: 'FWD', transmission: '8-Speed N DCT', mpgCity: 22, mpgHighway: 28, seating: 4 },
    features: ['Three-Door Design', 'N Performance Exhaust', 'Electronic LSD', 'Launch Control', 'Performance Bucket Seats', 'N Grin Shift Mode'],
  },

  // Kia
  {
    id: 37,
    make: 'Kia',
    model: 'Telluride',
    year: 2024,
    trim: 'SX Prestige',
    description: 'Three-row SUV with premium interior, Nappa leather, and 10.25-inch display',
    msrp: 49000,
    imageUrl: img('Kia', 'Telluride', 2024),
    type: 'SUV',
    specs: { engine: '3.8L Lambda II V6', horsepower: 291, drivetrain: 'AWD', transmission: '8-Speed Automatic', mpgCity: 19, mpgHighway: 24, seating: 8 },
    features: ['Nappa Leather Seating', 'Meridian Premium Audio', 'Heads-Up Display', '360° Surround View Monitor', 'Heated & Ventilated Seats', 'Dual 10.25" Touchscreens'],
  },
  {
    id: 38,
    make: 'Kia',
    model: 'K5',
    year: 2023,
    trim: 'GT-Line',
    description: 'Mid-size Sedan with sporty GT-Line exterior and turbocharged engine',
    msrp: 28500,
    imageUrl: img('Kia', 'K5', 2023),
    type: 'Sedan',
    specs: { engine: '1.6L Turbocharged I4', horsepower: 180, drivetrain: 'FWD', transmission: '8-Speed DCT', mpgCity: 28, mpgHighway: 38, seating: 5 },
    features: ['GT-Line Sport Styling', '10.25" Navigation Display', 'Wireless Apple CarPlay', 'Heated Front Seats', 'Drive Mode Select', 'Blind-Spot Collision Warning'],
  },
  {
    id: 39,
    make: 'Kia',
    model: 'Stinger',
    year: 2022,
    trim: 'GT2',
    description: 'Sport Sedan with twin-turbo V6 and rear-wheel drive performance',
    msrp: 46000,
    imageUrl: img('Kia', 'Stinger', 2022),
    type: 'Sedan',
    specs: { engine: '3.3L Twin-Turbo V6', horsepower: 368, drivetrain: 'RWD', transmission: '8-Speed Automatic', mpgCity: 17, mpgHighway: 25, seating: 5 },
    features: ['Brembo 4-Piston Front Brakes', 'Electronic LSD', 'Nappa Leather Interior', 'Harman Kardon Audio', 'Launch Control', 'Heads-Up Display'],
  },
  {
    id: 40,
    make: 'Kia',
    model: 'Soul',
    year: 2023,
    trim: 'GT-Line',
    description: 'Boxy Hatchback with unique design and available infinity audio system',
    msrp: 24000,
    imageUrl: img('Kia', 'Soul', 2023),
    type: 'Hatchback',
    specs: { engine: '2.0L 4-Cylinder', horsepower: 147, drivetrain: 'FWD', transmission: 'CVT', mpgCity: 27, mpgHighway: 33, seating: 5 },
    features: ['Panoramic Sunroof', 'Infinity 8-Speaker Audio', '10.25" Touchscreen', 'Wireless Charging', 'LED Signature Lighting', 'Drive Mode Select'],
  },

  // Nissan
  {
    id: 41,
    make: 'Nissan',
    model: 'Pathfinder',
    year: 2023,
    trim: 'Platinum',
    description: "Three-row SUV with captain's chairs and ProPilot Assist semi-autonomous driving",
    msrp: 49500,
    imageUrl: img('Nissan', 'Pathfinder', 2023),
    type: 'SUV',
    specs: { engine: '3.5L VQ V6', horsepower: 284, drivetrain: 'AWD', transmission: '9-Speed Automatic', mpgCity: 20, mpgHighway: 25, seating: 8 },
    features: ["Captain's Chairs (2nd Row)", 'ProPilot Assist', 'Bose Premium Audio', '12.3" Navigation Display', 'Around View Monitor', 'Tri-Zone Automatic Climate'],
  },
  {
    id: 42,
    make: 'Nissan',
    model: 'Altima',
    year: 2024,
    trim: 'SR AWD',
    description: 'Mid-size Sedan with all-wheel drive and ProPilot Assist technology',
    msrp: 30500,
    imageUrl: img('Nissan', 'Altima', 2024),
    type: 'Sedan',
    specs: { engine: '2.5L 4-Cylinder', horsepower: 182, drivetrain: 'AWD', transmission: 'CVT', mpgCity: 26, mpgHighway: 36, seating: 5 },
    features: ['ProPilot Assist', 'All-Wheel Drive', '8" Touchscreen', 'Apple CarPlay / Android Auto', 'Heated Front Seats', 'LED Headlights'],
  },
  {
    id: 43,
    make: 'Nissan',
    model: 'Frontier',
    year: 2023,
    trim: 'Pro-4X',
    description: 'Mid-size Truck with off-road Bilstein shocks and locking rear differential',
    msrp: 39500,
    imageUrl: img('Nissan', 'Frontier', 2023),
    type: 'Truck',
    specs: { engine: '3.8L DOHC V6', horsepower: 310, drivetrain: '4WD', transmission: '9-Speed Automatic', mpgCity: 16, mpgHighway: 22, seating: 5 },
    features: ['Bilstein Off-Road Shocks', 'Locking Rear Differential', 'Skid Plates', 'All-Terrain Tires', '9" Touchscreen', 'Off-Road Drive Mode'],
  },
  {
    id: 44,
    make: 'Nissan',
    model: 'Z',
    year: 2024,
    trim: 'Performance',
    description: 'Iconic sport Coupe with twin-turbo V6 and 6-speed manual transmission',
    msrp: 52500,
    imageUrl: img('Nissan', 'Z', 2024),
    type: 'Coupe',
    specs: { engine: '3.0L Twin-Turbo V6', horsepower: 400, drivetrain: 'RWD', transmission: '6-Speed Manual', mpgCity: 18, mpgHighway: 25, seating: 2 },
    features: ['6-Speed Manual Transmission', 'Sport-Tuned Suspension', 'Brembo Brakes', '12.3" Digital Cluster', 'Wireless Apple CarPlay', 'Rev Match Control'],
  },

  // Porsche
  {
    id: 45,
    make: 'Porsche',
    model: 'Cayenne',
    year: 2024,
    trim: 'S',
    description: 'Luxury SUV with 434hp twin-turbo V8 and Sport Chrono package',
    msrp: 92000,
    imageUrl: img('Porsche', 'Cayenne', 2024),
    type: 'SUV',
    specs: { engine: '4.0L Twin-Turbo V8', horsepower: 434, drivetrain: 'AWD', transmission: '8-Speed Tiptronic S', mpgCity: 16, mpgHighway: 22, seating: 5 },
    features: ['Sport Chrono Package', 'PASM Sport Suspension', 'Porsche InnoDrive', '14.9" Central Touchscreen', 'Burmester 3D Audio', 'Night Vision Assist'],
  },
  {
    id: 46,
    make: 'Porsche',
    model: '911',
    year: 2023,
    trim: 'Carrera 4S',
    description: 'Iconic sport Coupe with 3.0L flat-six turbo and all-wheel drive',
    msrp: 130000,
    imageUrl: img('Porsche', '911', 2023),
    type: 'Coupe',
    specs: { engine: '3.0L Twin-Turbo Flat-Six', horsepower: 443, drivetrain: 'AWD', transmission: '8-Speed PDK', mpgCity: 18, mpgHighway: 24, seating: 4 },
    features: ['Sport Chrono Package', 'PASM Adaptive Suspension', 'Porsche Torque Vectoring', 'PDCC Sport', 'Bose Surround Sound', 'Launch Control'],
  },
  {
    id: 47,
    make: 'Porsche',
    model: 'Boxster',
    year: 2022,
    trim: 'GTS 4.0',
    description: 'Mid-engine Convertible with naturally aspirated flat-six and PDK transmission',
    msrp: 89000,
    imageUrl: img('Porsche', 'Boxster', 2022),
    type: 'Convertible',
    specs: { engine: '4.0L Naturally Aspirated Flat-Six', horsepower: 394, drivetrain: 'RWD', transmission: '6-Speed PDK', mpgCity: 18, mpgHighway: 25, seating: 2 },
    features: ['Mid-Engine Layout', 'GTS Sport Exhaust', 'PASM Sport Suspension', 'GTS Interior Package', 'Bose Audio System', 'Launch Control'],
  },

  // Additional makes
  {
    id: 48,
    make: 'Subaru',
    model: 'Outback',
    year: 2023,
    trim: 'Onyx Edition XT',
    description: 'All-wheel drive SUV with 260hp turbocharged engine and roof rails',
    msrp: 38000,
    imageUrl: img('Subaru', 'Outback', 2023),
    type: 'SUV',
    specs: { engine: '2.4L Turbocharged H4', horsepower: 260, drivetrain: 'AWD', transmission: 'Lineartronic CVT', mpgCity: 23, mpgHighway: 30, seating: 5 },
    features: ['Symmetrical AWD', 'X-MODE Dual Function', 'StarTex Water-Repellent Interior', '11.6" Touchscreen', 'SUBARU STARLINK Safety', 'Raised Ground Clearance'],
  },
  {
    id: 49,
    make: 'Mazda',
    model: 'MX-5 Miata',
    year: 2024,
    trim: 'Grand Touring',
    description: 'Lightweight Convertible with Brembo brakes and Recaro sport seats',
    msrp: 36000,
    imageUrl: img('Mazda', 'MX-5 Miata', 2024),
    type: 'Convertible',
    specs: { engine: '2.0L SKYACTIV-G I4', horsepower: 181, drivetrain: 'RWD', transmission: '6-Speed Automatic', mpgCity: 26, mpgHighway: 35, seating: 2 },
    features: ['Brembo Front Brakes', 'Recaro Sport Seats', 'Power Retractable Soft Top', '7" Infotainment Display', 'Bilstein Shocks', 'Heated Front Seats'],
  },
  {
    id: 50,
    make: 'Volkswagen',
    model: 'Golf GTI',
    year: 2023,
    trim: 'Autobahn',
    description: 'Hot Hatchback with 241hp turbocharged engine and DCC adaptive suspension',
    msrp: 37500,
    imageUrl: img('Volkswagen', 'Golf GTI', 2023),
    type: 'Hatchback',
    specs: { engine: '2.0L Turbocharged I4', horsepower: 241, drivetrain: 'FWD', transmission: '7-Speed DSG', mpgCity: 24, mpgHighway: 32, seating: 5 },
    features: ['DCC Adaptive Suspension', 'IQ.DRIVE Driver Assistance', '10" Touchscreen', 'VW Digital Cockpit Pro', 'Harman Kardon Audio', 'Sport Front Seats'],
  },
];
